function [BW,maskedImage] = segmentImageXZ(X)
%segmentImage Segment image using auto-generated code from imageSegmenter App
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter App. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 25-Apr-2017
%----------------------------------------------------


% Create empty mask.
BW = false(size(X,1),size(X,2));

% イメージのしきい値処理 - グローバルしきい値
BW = imbinarize(X);

% マスクの反転
BW = imcomplement(BW);

% 境界のクリア
BW = imclearborder(BW);

% 穴の塗りつぶし
BW = imfill(BW, 'holes');

% disk によるマスクの収縮
radius = 15;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imerode(BW, se);

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;